version: "3.8"

services:
  web:
    build:bassam2080/myapp4-web:1.0
    volumes:
      - ./site:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
      -./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker_database
volumes:
  db_data:
